import { mkdir, writeFile } from "node:fs/promises";
const root = new URL('.', import.meta.url).pathname;
const email = 'imperiumgym.mazara@gmail.com';
const pages = {
  ar: { dir:'rtl', lang:'ar', home:'الصفحة الرئيسية', download:'تحميل التطبيق', privacy:'سياسة الخصوصية', support:'الدعم وطلبات الحذف', title:'سياسة الخصوصية', intro:'صُمم Imperium Gym ليبقى التحكم في البيانات بيد المستخدم.', local:'يتم حفظ الملف الشخصي المحلي ورمز الدخول وسجلات التمارين على الهاتف. لا تُرسل هذه البيانات إلى خادم عند استخدام الوضع المحلي.', cloud:'المزامنة السحابية اختيارية. عند تسجيل الدخول، يمكن حفظ سجلات التمارين لمزامنتها بين الأجهزة.', rights:'يمكنك حذف البيانات المحلية من إعدادات الهاتف. لطلب حذف البيانات السحابية، استخدم صفحة الدعم.', help:'للحصول على المساعدة أو طلب حذف بيانات السحابة، اذكر الاسم والبريد المستخدمين للمزامنة.' },
  fr: { dir:'ltr', lang:'fr', home:'Accueil', download:'Télécharger l’application', privacy:'Politique de confidentialité', support:'Support et suppression', title:'Politique de confidentialité', intro:'Imperium Gym est conçue pour laisser le contrôle des données à l’utilisateur.', local:'Le profil local, le code PIN et les séances sont enregistrés sur l’appareil. Ces données ne sont pas envoyées à un serveur en mode local.', cloud:'La synchronisation cloud est facultative. Après connexion, les séances peuvent être enregistrées pour être synchronisées entre appareils.', rights:'Vous pouvez supprimer les données locales depuis les réglages du téléphone. Pour supprimer des données cloud, utilisez la page de support.', help:'Pour obtenir de l’aide ou demander la suppression de données cloud, indiquez le nom et l’e-mail utilisés pour la synchronisation.' },
  it: { dir:'ltr', lang:'it', home:'Home', download:'Scarica l’app', privacy:'Informativa sulla privacy', support:'Supporto e cancellazione', title:'Informativa sulla privacy', intro:'Imperium Gym è progettata per lasciare il controllo dei dati all’utente.', local:'Il profilo locale, il PIN e gli allenamenti vengono salvati sul dispositivo. In modalità locale questi dati non vengono inviati a un server.', cloud:'La sincronizzazione cloud è facoltativa. Dopo l’accesso, gli allenamenti possono essere salvati per la sincronizzazione tra dispositivi.', rights:'Puoi cancellare i dati locali dalle impostazioni del telefono. Per cancellare i dati cloud, usa la pagina di supporto.', help:'Per assistenza o per richiedere la cancellazione dei dati cloud, indica il nome e l’e-mail usati per la sincronizzazione.' }
};
const shell = (t, body) => `<!doctype html><html lang="${t.lang}" dir="${t.dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Imperium Gym — ${t.title}</title><link rel="stylesheet" href="../../style.css"></head><body><main class="legal"><article><a class="back" href="../../">← ${t.home}</a><p class="eyebrow">IMPERIUM GYM / OFFICIAL</p>${body}<footer><a href="mailto:${email}">${email}</a><a href="../../download/${t.lang}/">${t.download}</a></footer></article></main></body></html>`;
for (const [lang,t] of Object.entries(pages)) {
  const privacy = `<h1>${t.title}</h1><p class="lead">${t.intro}</p><h2>01 / ${lang === 'ar' ? 'البيانات المحلية' : lang === 'fr' ? 'Données locales' : 'Dati locali'}</h2><p>${t.local}</p><h2>02 / ${lang === 'ar' ? 'المزامنة السحابية' : lang === 'fr' ? 'Synchronisation cloud' : 'Sincronizzazione cloud'}</h2><p>${t.cloud}</p><h2>03 / ${lang === 'ar' ? 'التحكم والحذف' : lang === 'fr' ? 'Contrôle et suppression' : 'Controllo e cancellazione'}</h2><p>${t.rights}</p><p><a class="support-link" href="../../support/${lang}/">${t.support} →</a></p>`;
  const support = `<h1>${t.support}</h1><p class="lead">${t.help}</p><h2>${lang === 'ar' ? 'قناة الدعم الرسمية' : lang === 'fr' ? 'Canal officiel' : 'Canale ufficiale'}</h2><p><a class="support-link" href="mailto:${email}">${email}</a></p><h2>${lang === 'ar' ? 'طلب حذف البيانات' : lang === 'fr' ? 'Demande de suppression' : 'Richiesta di cancellazione'}</h2><p>${t.rights}</p><p><a class="support-link" href="../../privacy/${lang}/">${t.privacy} →</a></p>`;
  await mkdir(`${root}privacy/${lang}`, {recursive:true}); await mkdir(`${root}support/${lang}`, {recursive:true});
  await writeFile(`${root}privacy/${lang}/index.html`, shell(t, privacy)); await writeFile(`${root}support/${lang}/index.html`, shell(t, support));
}
